    MODEL SMALL 
    .DATA
    MSG DB 'ESCREVA UM NUMERO ALEATORIO DE 0 A 9: $'
    MSG2 DB 'AGORA OUTRO NUMERO: $'
    MSG3 DB 'A SOMA DESSES DOIS NUMEROS: $'

    .CODE
    MAIN PROC

    MOV AX, @DATA
    MOV DS, AX

    MOV AH, 9   ;MOSTRA A STRING
    LEA DX, MSG
    INT 21h

    MOV AH, 1 ;PEDE AO USUARIO UM CARACTER 
    INT 21h

    MOV BL, AL  ;SALVA O CARACTER
    SUB BL, 30H ;TRANSFORMA O CARACTER EM NUMERO

    MOV AH, 02 ;PULA LINHA 
    MOV DL, 10
    INT 21h
;PRIMEIRA MENSAGEM

    MOV AH, 9
    LEA DX, MSG2
    INT 21h

    MOV AH, 1
    INT 21h

    MOV CL, AL
    SUB CL, 30H

    MOV AH, 02
    MOV DL, 10
    INT 21h
; SEGUNDA MENSAGEM 

    MOV AH, 9   
    LEA DX, MSG3
    INT 21h

    ADD CL, BL ;ADC O CONTEUDO DE BL PARA CL OS SOMANDO
    MOV DL, CL ; MANDA O CONTEUDO DE CL PARA DL
    ADD DL, 30H ;TRANSFORMA EM CARACTER DE NOVO
    MOV AH, 2
    INT 21h

;TERCEIRA MENSAGEM MOSTRANDO O RESULTADO 


MAIN ENDP
END MAIN