    MODEL SMALL 
    .DATA
    MSG DB 'ESCREVA UMA LETRA: $'
    MSG2 DB 'A LETRA EM MAISCULO E: $'

    .CODE
    MAIN PROC

    MOV AX, @data
    MOV DS, AX

    MOV AH, 9   ;MOSTRA A STRING
    LEA DX, MSG
    INT 21h

    MOV AH, 1   ;PEDE AO USUARIO DIGITAR
    INT 21h

    MOV BL, AL ;SALVA O CARACTER DIGITADO

    MOV AH, 2
    MOV DL, 10
    INT 21h

    MOV AH, 9   
    LEA DX, MSG2
    INT 21h

    MOV AH, 2   ;MOSTRA O CARACTER SALVO
    SUB BL, 32 ;SUBSTITIUI O CARACTER POR MAIUSCULO
    MOV DL, BL ;MOSTRA NA TELA O RESULTADO
    INT 21h

    MAIN ENDP
    END MAIN
